services:
  - type: static
    name: toolboxpay-v3.0
    env: static
    buildCommand: null
    publishDir: .
    routes:
      - type: rewrite
        source: /
        destination: /app-final.html
      - type: rewrite
        source: /index.html
        destination: /app-final.html
